bundles/org.eclipse.cdt.lsp.editor.ui.test/.classpath, bundles/org.eclipse.cdt.lsp.editor.ui.test/.project, bundles/org.eclipse.cdt.lsp.editor.ui.test/.settings/org.eclipse.jdt.core.prefs, bundles/org.eclipse.cdt.lsp.editor.ui.test/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp.editor.ui.test/build.properties, bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/TestUtils.java, bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/preference/LspEditorPreferencesTesterTest.java, bundles/org.eclipse.cdt.lsp.test/.classpath, bundles/org.eclipse.cdt.lsp.test/.project, bundles/org.eclipse.cdt.lsp.test/.settings/org.eclipse.jdt.core.prefs, bundles/org.eclipse.cdt.lsp.test/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp.test/build.properties, bundles/org.eclipse.cdt.lsp.test/fragment.xml, bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/server/CLanguageServerProviderTest.java, bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/server/MockCLanguageServerProvider.java
Please review the initial unit tests
=> Add unit tests

.github/workflows/tycho-build.yaml, bundles/org.eclipse.cdt.lsp.editor.ui.test/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/preference/LspEditorPreferencesTesterTest.java, bundles/org.eclipse.cdt.lsp.test/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/server/CLanguageServerProviderTest.java, pom.xml
This is a series of commits (that also includes PR #17) that gets tests running on GitHub Actions.
=> Fix Maven Tycho tests in CI

bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/preference/LspEditorPreferencesTesterTest.java, bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/preference/LspEditorPreferencesTester.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspPlugin.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/editor/CEditorAssociationOverride.java
=> Define C-Editor IDs in one place

pom.xml, releng/org.eclipse.cdt.lsp.target/.project, releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target
Added releng/org.eclipse.cdt.lsp.target
Renamed root module to "org.eclipse.cdt.lsp.root" for consistency
=> Repository should have dedicated target definition #34

.github/workflows/licensecheck.yml
Add yml configuration to check licenses
Fixes #49
=> [#49] Employ Eclipse Dash license check

features/org.eclipse.cdt.lsp.feature/.project, features/org.eclipse.cdt.lsp.feature/.settings/org.eclipse.core.resources.prefs, features/org.eclipse.cdt.lsp.feature/build.properties, features/org.eclipse.cdt.lsp.feature/feature.properties, features/org.eclipse.cdt.lsp.feature/feature.xml, pom.xml
Added "C/C++ LSP Support" feature
Fixes https://github.com/eclipse-cdt/cdt-lsp/issues/57
=> [#57] Add org.eclipse.cdt.lsp.feature

bundles/org.eclipse.cdt.lsp/language-configurations/language-configuration.json
Small change for multi line auto completion as discussed in issue #80.
=> [#80] Add auto closing pair for multi line comment

bundles/org.eclipse.cdt.lsp/plugin.xml
=> [#85] Always use cpp grammar for .h files

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspPlugin.java
=> [#88] Fix: Grammar warnings spam stderr

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspPlugin.java
=> [#101] Make logger suppression narrower

bundles/org.eclipse.cdt.lsp.clangd/.project, bundles/org.eclipse.cdt.lsp.clangd/.settings/org.eclipse.pde.ds.annotations.prefs, bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/org.eclipse.cdt.lsp.internal.clangd.ClangdFallbackManager.xml, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/BaseClangdLanguageServerProvider.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdFallbackFlags.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdFallbackManager.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdLanguageServerProvider.java, bundles/org.eclipse.cdt.lsp/.project, bundles/org.eclipse.cdt.lsp/.settings/org.eclipse.pde.ds.annotations.prefs, bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp/OSGI-INF/org.eclipse.cdt.lsp.internal.InitialFileManager.xml, bundles/org.eclipse.cdt.lsp/build.properties, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/InitialUri.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspPlugin.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspUtils.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/InitialFileManager.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/enable/HasLanguageServerPropertyTester.java
Extract interfaces and register OSGi components
Remove LspPlugin#getWorkspace
=> [#104] Employ OSGi components for Clangd FallbackFlags

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target
=> Update CDT version to 11.2.0

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsContentProvider.java
When the document for a given file has not been loaded yet (opened in LSP based editor), it will be loaded as temporary document. This temporary document shall be disconnected from file buffer when the refresh tree content has been finished.
fixes #112
=> Load document temporary if not yet existing

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdPreferredOptions.java
=> [#118] fix query driver option

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdPlugin.java
=> Remove unused preference store

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdMetadata.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdOptions.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdMetadataDefaults.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdPreferredOptions.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationArea.java
Add custom options preference as discussed in issue #81. See also #142.
=> [#81] Add custom options preference

bundles/org.eclipse.cdt.lsp/plugin.xml, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/editor/LspEditorFileImageDescriptor.java
=> [#159] Add C file image descriptor

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target
=> Fix target dependencies

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdConfigurationAccess.java
=> [#166] Allow empty Completion and Drivers field

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationArea.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/LspEditorUiMessages.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/LspEditorUiMessages.properties
=> [#172] fix filter path in clangd file dialog

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationArea.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationPage.java
=> [#176] fix Editor (LSP) project properties enable bug

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target
=> Use the same target file for CDT LSP as CDT

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsContentProvider.java
IFileBuffer.getContentType() throws an exception when the underlying resource does not exists.
fixes #182
=> [#182] Fix ResourceException when 'Save As...' on text file in workspace

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/messages/LspUiMessages.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/messages/LspUiMessages.properties, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsContentProvider.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/SymbolsManager.java
i.e. in the Project Explorer view
fixes #184
=> [#184] fix UI freezes when opening TU children

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target
Bring cdt-lsp up to changes in https://github.com/eclipse-cdt/cdt/pull/541
=> Update to latest dependencies in cdt-lsp's target

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationPage.java
=> [#200] Open UI dialog only when clangd LS active

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationPage.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspUtils.java
to prevent ID string proliferating
=> move getStartedWrappers to LspUtils

features/org.eclipse.cdt.lsp.feature/feature.xml, pom.xml, releng/org.eclipse.cdt.lsp.repository/pom.xml
=> Version bumps for CDT LSP 1.1.0

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdLanguageServerProvider.java
=> [#220] Support environment variables in clangd options

.github/workflows/licensecheck.yml
Adding pull-requests right according to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3996
=> Adding pull-requests right

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdConfigFileChecker.java
=> [#250] Add context info to .clangd yaml problem marker

features/org.eclipse.cdt.lsp.feature/feature.xml, pom.xml, releng/org.eclipse.cdt.lsp.repository/pom.xml
=> Version bumps for CDT LSP 2.0.0

CODE_OF_CONDUCT.md, NOTICE.md, SECURITY.md
* added CODE_OF_CONDUCT.md
* added NOTICE.md
* added SECURITY.md
=> [#279] Add required root files

bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/l10n/bundle.properties, bundles/org.eclipse.cdt.lsp.clangd/plugin.xml
=> [#273] Add find references to editors context menu

bundles/org.eclipse.cdt.lsp/plugin.xml
=> [#292] Show Save Action in project properties only

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/CompileCommandsMonitor.java
Always restart language servers when compile database changes. See #302
=> [#302] Improve restarting mechanism for compile database

jenkins/pod-templates/cdt-full-pod-plus-eclipse-install.yaml
Update images to Dockerfiles from CDT commit https://github.com/eclipse-cdt/cdt/commit/b433dfad029ed2fe4556c59d62d45708d55a8328
=> Update images to Dockerfiles from CDT commit b433dfad0

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target
since he latest lsp4e requires the latest version of mylyn, we have to them as well.
=> fix broken build - add missing latest mylyn dependency

examples/org.eclipse.cdt.lsp.examples.preferences/META-INF/MANIFEST.MF, examples/org.eclipse.cdt.lsp.examples.preferences/src/org/eclipse/cdt/lsp/examples/preferences/MyClangdOptionsDefaults.java
MyClangdOptionsDefaults has to implement ClangdOptionsDefaults instead of extending the now non-API class BuiltinClangdOptionsDefaults
fixes #314
=> [#314] fix broken API

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/CompileCommandsMonitor.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ClangdConfigurationPage.java
due to some LSP4E refactoring we had to align some fixes as well.
=> fix broken LSP4E API

pom.xml
as mentioned here:
https://github.com/eclipse-cdt/cdt-lsp/pull/265#issuecomment-2138840435
=> Use exact cdt-lsp release api-baseline

features/org.eclipse.cdt.lsp.feature/build.properties, features/org.eclipse.cdt.lsp.feature/p2.inf
=> [#340] Add cdt-lsp latest URL to available software sites

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp.clangd/plugin.xml
=> [#350] Provide yaml syntax highlighting for clangd config files

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/ui/navigator/SymbolsManager.java
as long as compileUnit.isDirty == true, the tree tries to fetch the children on the translation unit. The reason why compileUnit.isDirty was assigned to response == null, was when a TimeoutException may occur. This has been considered.
fixes #358
=> [#358] fix endless call loop of TU children in project explorer

bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
otherwise the LS restart would throw an exception
=> update LSP4E dependency

.github/workflows/licensecheck.yml, CONTRIBUTING.md, README.md, RELEASING.md
Part of https://github.com/eclipse-cdt/cdt-lsp/issues/384
=> Update references to master branch (replaced with main)

bundles/org.eclipse.cdt.lsp.clangd/plugin.xml, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/format/ClangFormatFileMonitor.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/format/ClangFormatValidator.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/format/RegexMarkerPattern.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/plugin/ClangdPlugin.java
=> [#398] Inform user about error in .clang-format file on file change

examples/org.eclipse.cdt.lsp.examples.preferences/OSGI-INF/org.eclipse.cdt.lsp.examples.preferences.MyClangdOptionsDefaults.xml
Fixes https://github.com/eclipse-cdt/cdt-lsp/issues/426
=> Update example service component for recent interface name change

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/config/ConfigurationMetadataBase.java
* add "override" method for the rest of supported preference types
=> [#429] Complete the implementation of `ConfigurationMetadataBase`

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdMetadata.java, bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdMetadataDefaults.java, bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/config/ConfigurationMetadataBase.java, examples/org.eclipse.cdt.lsp.examples.preferences/src/org/eclipse/cdt/lsp/examples/preferences/MyClangdOptionsDefaults.java
* add facilities to оverride just one preference
=> [#427] Override just one preference in my extension to CDT LSP

bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/l10n/bundle.properties, bundles/org.eclipse.cdt.lsp.clangd/plugin.xml
=> [#393] add Open Declaration F3 to context menu

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangFormatFileHandler.java
=> [#445] Use WorkspaceJob instead of WorbenchJob

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdCompilationDatabaseSetter.java
=> [#476] Update .clangd file on .prefs changes

CHANGELOG.md, README.md
=> Add CDT-LSP 3.1.0 to changelog and readme

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp.doc/META-INF/MANIFEST.MF, bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF, examples/org.eclipse.cdt.lsp.examples.preferences/META-INF/MANIFEST.MF, features/org.eclipse.cdt.lsp.feature/feature.xml, pom.xml, releng/org.eclipse.cdt.lsp.repository/pom.xml
=> Prepare repo for CDT LSP 3.2.0

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdMetadata.java
=> [#498] Log clangd error messages only as default

bundles/org.eclipse.cdt.lsp/plugin.xml
=> [#508] add Ctrl+/ keybinding for toggle line comment

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdCompilationDatabaseSetter.java
=> fix: re-create .clangd file in CMake projects when it gets deleted
