eclipse-cdt/cdt-lsp

org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/CLanguageServerRegistry.java
org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspPlugin.java

The order of assigning plugin=this and CLanguageServerRegistry matter as CLanguageServerRegistry can log errors and if plugin isn't assigned before CLanguageServerRegistry is created the logging methods hit an NPE
Also, added a descriptive message to the log entry.

Ensure log message about expression creation makes it log

---

bundles/org.eclipse.cdt.lsp.editor.ui.test/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.test/META-INF/MANIFEST.MF

It must be org.junit.jupiter.api

Fix wrong bundle name in Eclipse 2022-06

---

bundles/org.eclipse.cdt.lsp.editor.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/CdtCLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/LspEditorUiMessages.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/LspEditorUiMessages.properties
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/LspEditorUiPlugin.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/preference/LspEditorPreferencePage.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/preference/LspEditorPreferences.java
bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/server/MockCLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/DefaultCLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/ICLanguageServerProvider.java

The server path and options can be edited for the used server provider. The default values are the commands delivered from the server provider.
In Windows it looks like this:
TODO: add tests and create a new issue for the topic that the LS has to be restarted when the server binary or options changes

Feature: edit server path and options in preference page

---

bundles/org.eclipse.cdt.lsp.editor.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/LspEditorUiPlugin.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/clangd/CompileCommandsMonitor.java

Update open editors when compile_commands.json file of the project of the edited file is added/removed/changed.
This makes use of clangd hot-reload, see https://reviews.llvm.org/D92663.
I thought it should be possible to notify clangd via didChangeWatchedFiles, however clangd receives the command but doesn't seem to update the compilation data base.

[#23] Refresh open editors when compile_commands.json changes

---

bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/preference/LspEditorPreferencesTesterTest.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/clangd/CompileCommandsMonitor.java
bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/LspUtilsTest.java
bundles/org.eclipse.cdt.lsp/plugin.xml
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspUtils.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/editor/CEditorAssociationOverride.java

The org.eclipse.tm4e.language_pack plug-in adds content types for C/C++ files. These content types needs to be considered during filtering

[#26] add missing contentTypeBindings

---

bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp/plugin.xml

Basic support of toggle line breakpoints in C/C++ Editor (LSP)

---

bundles/org.eclipse.cdt.lsp.editor.ui.test/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/TestUtils.java
bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/clangd/ClangdConfigurationManagerTest.java
bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/preference/LspEditorPreferencesTesterTest.java
bundles/org.eclipse.cdt.lsp.editor.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/LspEditorUiMessages.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/LspEditorUiMessages.properties
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/LspEditorUiPlugin.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/clangd/CProjectChangeMonitor.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/clangd/ClangdConfigurationManager.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/preference/LspEditorPreferencesTester.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspUtils.java
releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

Generates or updates the CompilationDatabase entry in the .clangd yaml file.

Clangd configuration file (.clangd) manager

---

bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/clangd/CProjectChangeMonitor.java

fix NPE in CProjectChangeMonitor (#52)

---

bundles/org.eclipse.cdt.lsp.editor.ui.test/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/commands/LspEditorActiveTesterTest.java
bundles/org.eclipse.cdt.lsp.editor.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.editor.ui/build.properties
bundles/org.eclipse.cdt.lsp.editor.ui/plugin.properties
bundles/org.eclipse.cdt.lsp.editor.ui/plugin.xml
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/commands/LspEditorActiveTester.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/commands/ToggleSourceAndHeaderCommandHandler.java
bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp/plugin.xml
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/services/ClangdLanguageServer.java
releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

- add server interface for clangd textDocument/switchSourceHeader extension
- add command and menu entry for switch action
Note: In the UI the term "toggle" is used instead of switch in order to be consistent with the CDT editor.
Fixes #47

[#47] Add action to switch between Source/Header

---

bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/preference/LspEditorPreferencesTester.java
bundles/org.eclipse.cdt.lsp/plugin.xml
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsContentProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsOpenActionProvider.java

Uses the LSP to fetch the children of a TU in the project explorer view.
fixes #36

[#36] Add new content provider using LSP

---

bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/clangd/CProjectChangeMonitor.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/preference/LspEditorPreferencesTester.java

In case the language server will be provided by a different plug-in, the enable check from that provider shall be used.

Use LS enable tester from active language server provider

---

pom.xml
releng/org.eclipse.cdt.lsp.repository/category.xml

Added p2 repository manifest
Fixes https://github.com/eclipse-cdt/cdt-lsp/issues/59

[#59] Add org.eclipse.cdt.lsp.repository to produce p2 artifacts

---

bundles/org.eclipse.cdt.lsp.editor.ui.test/src/org/eclipse/cdt/lsp/editor/ui/test/preference/LspEditorPreferencesTesterTest.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/preference/LspEditorPreferencesTester.java
bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/LspUtilsTest.java
bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/TestUtils.java
bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/server/enable/HasLanguageServerPropertyTesterTest.java
bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspPlugin.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspUtils.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/editor/CEditorAssociationOverride.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/DefaultCLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/ICLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/enable/HasLanguageServerPropertyTester.java

Moved code from org.eclipse.cdt.lsp.editor.editor.ui to org.eclipse.cdt.lsp plug-in.
Reasons:
- The logic for the check whether to open a C/C++ source file in the LSP based editor or not should be done in the org.eclipse.cdt.lsp plug-in, since the org.eclipse.ui.ide.editorAssociationOverride extension point is here as well.
- The org.eclipse.cdt.lsp.editor.editor.ui has to check whether the prefer LSB Editor has been set in the project properties or not on a given project.
- Replaced argument type Object in ICLanguageServerProvider.isEnabledFor by IProject. This makes it clearly to implement a test.

Refactor LS enable

---

pom.xml
releng/org.eclipse.cdt.lsp.repository/category.xml

Added source UIs generation and repository entries
Fixes https://github.com/eclipse-cdt/cdt-lsp/issues/66

[#66] Add source bundles and features to CDT LSP repository

---

bundles/org.eclipse.cdt.lsp.clangd/.classpath
bundles/org.eclipse.cdt.lsp.clangd/.project
bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/l10n/bundle.properties
bundles/org.eclipse.cdt.lsp.clangd/about.html
bundles/org.eclipse.cdt.lsp.clangd/build.properties
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/editor/.gitkeep
features/org.eclipse.cdt.lsp.feature/feature.xml

Added "org.eclipse.cdt.lsp.clangd" bundle as a placeholder for clangd-specific code
Fixes https://github.com/eclipse-cdt/cdt-lsp/issues/65

[#65] Add "org.eclipse.cdt.lsp.clangd" bundle

---

bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/LspEditorUiPlugin.java
bundles/org.eclipse.cdt.lsp.editor.ui/src/org/eclipse/cdt/lsp/editor/ui/clangd/CProjectChangeMonitor.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspPlugin.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspUtils.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/server/CLanguageServerRegistry.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/EnableExpression.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsContentProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsOpenActionProvider.java

Switch to standard `Platform.getLog(Class<?>)`
Fixes https://github.com/eclipse-cdt/cdt-lsp/issues/50

[#50] Refactor static log methods

---

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF

Otherwise the class
"org.eclipse.cdt.lsp.internal.clangd.CdtCLanguageServerProvider" can't be instantiated by "org.eclipse.cdt.lsp" in extension point.

Add lazy bundle activation

---

README.md
bundles/org.eclipse.cdt.lsp.clangd/plugin.xml
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/LspEditorUiPlugin.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/expressions/LspEditorActiveTester.java

All except PLUGIN_ID itself are reworked
PLUGIN_ID rework will follow together with preference rework, see https://github.com/eclipse-cdt/cdt-lsp/issues/83
Required for https://github.com/eclipse-cdt/cdt-lsp/issues/77

[#77] Remove/replace old plugin path "org.eclipse.cdt.lsp.editor.ui"

---

bundles/org.eclipse.cdt.lsp.test/fragment.xml

the id of the property test has been renamed in #84. This file was missed.

Fix old property test

---

bundles/org.eclipse.cdt.lsp.clangd/.classpath
bundles/org.eclipse.cdt.lsp.test/.classpath
bundles/org.eclipse.cdt.lsp/.classpath

Since Java 17 compliance has been activated, we have to use JRE 17.
Otherwise the error: "The project was not built due to "release 17 is not found in the system". Fix the problem, then try refreshing this project and building it since it may be inconsistent" occurs.

Set java 17 in classpath

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/CdtCLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdFallbackManager.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/InitialFileManager.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspUtils.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/server/CLanguageServerStreamConnectionProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/ICLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/enable/HasLanguageServerPropertyTester.java

clangd has trouble on Windows machines to detect the system headers. Therefore we add the includes paths from the first project file opened by the LS client to the fallbackFlags.
see https://clangd.llvm.org/extensions#compilation-commands
LIMITATION: The include path detection by
ICBuildConfiguration.getScannerInformation works currently only for the clang compiler. g++/gcc doesn't work.
fixes #87

[#87] Set clangd fallbackFlags on Windows

---

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.clangd/plugin.xml
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/BaseClangdLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdFallbackManager.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/preferences/LspEditorPreferencePage.java
bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/server/MockCLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/editor/CEditorAssociationOverride.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/server/CLanguageServerRegistry.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/server/CLanguageServerStreamConnectionProvider.java

[#105] Move and rename DefaultCLanguageServerProvider

---

bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/editor/CEditorAssociationOverride.java

prior to open a file with the LSP based C/C++ editor. When a C/C++ file has been opened prior by the old CDT C/C++ editor the codan markers are persistent and must be removed from the resource.
fixed #41

[#41] Delete codan markers

---

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target
tests/org.eclipse.cdt.lsp.clangd.tests/META-INF/MANIFEST.MF

I am trying to setup the project for the first time and reliased we need to update to the target to the latest plugins.
- Update to the latest CDT 11.1
- Update to the latest release eclipse orbit R20230302014618 and updated mockito plugin accordingly
https://download.eclipse.org/tools/orbit/downloads/
https://download.eclipse.org/tools/orbit/downloads/drops/R20230302014618/

Target Update: Update to CDT 11.1 and latest Orbit

---

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/CProjectChangeMonitor.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdPlugin.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/CompileCommandsMonitor.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/handlers/ToggleSourceAndHeaderCommandHandler.java

[#121] rename LspEditorUiPlugin into ClangdPlugin

---

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.clangd/plugin.xml
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/expressions/ClangdLanguageServerProviderActive.java

hide pages when the ClangdLanguageServerProvider is not used.
see this [comment in #81](https://github.com/eclipse-cdt/cdt-lsp/issues/81#issuecomment-1589290227)

[#81] hide clangd property and preference pages

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdFallbackManager.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ResolveProject.java
bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/ExistingResourceTest.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ExistingResource.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/InitialFileManager.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/enable/HasLanguageServerPropertyTester.java

Rename `UriResource` to `ExistingResource` and add tests, since original implementation just always return what it was asked for, without considering its existance.

[#134] Fix broken fallback flags

---

bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp/plugin.xml
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/editor/DebugHoverProvider.java
releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

Adds a hover provider which delegates to the cdt debug hover mechanism.
Fixes issue #70.
Requires the following pull requests to be merged:
https://github.com/eclipse-cdt/cdt/pull/396
https://github.com/eclipse-platform/eclipse.platform.text/pull/200

[#70] Add hover provider for debugging

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspPlugin.java

Keep a reference to the logger, otherwise it will be garbage collected and a new logger will be used in tm4e which has a different warning level.
See also #101.

[#88] Fix: Grammar warnings spam stderr

---

bundles/org.eclipse.cdt.lsp.clangd/plugin.xml
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationPage.java

This allows a vendor to change the visibility of the clangd preference and property page separately.
Fixes #151

[#151] Use unique id for clangd property and preference page

---

bundles/org.eclipse.cdt.lsp/plugin.xml
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/server/enable/HasLanguageServerPropertyTester.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsContentProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/CSymbolsOpenActionProvider.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/navigator/FileBufferListenerAdapter.java
releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

the symbols has not been cached and due to the disconnect of the file from buffer every call of refreshTreeContentFromLS triggers a new AST build on server side for the file. This can take a while for a large codebase. The solution is to cache the symbols for a file in the SymbolsContainer. The symbols will only be refreshed when the buffer is dirty.
Replaced the deprecated DocumentSymbolWithFile by DocumentSymbolWithURI
fixes #139

[#139] fix slow content provider

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationArea.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationPage.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/LspEditorUiMessages.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/LspEditorUiMessages.properties

Ask the user to restart clangd when a clangd option has been modified in
the prefs or project properties. We stop the clangd language server.
When the user opens a new C/C++ file or an already opened C/C++ file in
the LSP based C/C++ editor gets into focus, a new LS will be started by
LSP4E.
Added a 'clangd options' group to the preference page. If any element in
this group will be modified, a info dialog pops up, when the 'Apply' or
'Apply and Close' button will be pressed. The dialog asks the user to
restart clangd.
fixes #150

[#150] Restart clangd when clangd settings changed

---

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

Note that 3rd party dependencies still need synchronizing with CDT, this commit contains only the Eclipse published dependency changes.
This is needed to fufill https://github.com/eclipse-cdt/cdt-lsp/pull/162#issuecomment-1664282922

Update to latest CDT and CDT dependencies

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdConfigurationVisibility.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationArea.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/DefaultClangdConfigurationVisibility.java

When clangd options are hidden in the project properties, the user has no idea which clangd optins are used, because even if they are hidden they are still in use when 'Enable project-specific settings' and 'Prefer C/C++ Editor (LSP)' is enabled.
fixes #189

remove clangd options hiding

---

bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/org.eclipse.cdt.lsp.internal.clangd.ClangdConfigurationAccess.xml
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdConfigurationVisibility.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdEnable.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdConfigurationAccess.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdLanguageServerProvider.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/ClangdPreferredOptions.java
examples/org.eclipse.cdt.lsp.examples.preferences/META-INF/MANIFEST.MF
examples/org.eclipse.cdt.lsp.examples.preferences/OSGI-INF/org.eclipse.cdt.lsp.examples.preferences.HidePreferClangd.xml
examples/org.eclipse.cdt.lsp.examples.preferences/OSGI-INF/org.eclipse.cdt.lsp.examples.preferences.MyClangdEnable.xml
examples/org.eclipse.cdt.lsp.examples.preferences/build.properties
examples/org.eclipse.cdt.lsp.examples.preferences/src/org/eclipse/cdt/lsp/examples/preferences/HidePreferClangd.java
examples/org.eclipse.cdt.lsp.examples.preferences/src/org/eclipse/cdt/lsp/examples/preferences/MyClangdEnable.java

This allows vendors to enable clangd and the LSP based C/C++ Editor based on certain project properties (e.g. the project nature)
fixes #188

[#188] add OSGi service to enable clangd via project properties

---

bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF

we should use at least 0.17.1 since there are several major improvements for our first release.

update LSP4E dependency

---

Jenkinsfile
releng/org.eclipse.cdt.lsp.repository/.project
releng/org.eclipse.cdt.lsp.repository/pom.xml

Includes removing version number from the zip file with the new pom.xml. This make writing the promotion scripts easier.
Part of https://github.com/eclipse-cdt/cdt-lsp/issues/197

Save the zip file of the repository as part of the artifacts

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/internal/clangd/editor/ClangdConfigurationPage.java

Since the LanguageServerWrapper provides a restart method we should use this method instead of stop(). See
https://github.com/eclipse/lsp4e/issues/839

Use restart() method from LanguageServerWrapper

---

bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/LspUtilsTest.java
bundles/org.eclipse.cdt.lsp/plugin.xml
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/LspUtils.java

Since this https://github.com/eclipse/tm4e/pull/500 lsp4e issue has been closed by this platform fix:
https://github.com/eclipse-platform/eclipse.platform/issues/151 we can now remove the contentTypeBinding to the lsp4e C++ content type definition.
fixes #224

[#224] remove obsolete tm4e Cpp content type binding

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/services/ast/AstNode.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/services/ast/AstParams.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/services/symbolinfo/RangeAndUri.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/services/symbolinfo/SymbolDetails.java
releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

I wondered why my last PR #256 didn't compile in the first place. It turns out, it's because the target definition file uses some repository locations pointing to snapshots instead of releases. I suppose that should be changed before releasing CDT LSP 1.1.0, right @ghentschke? This PR should do exactly that.
PR #256 didn't compile, because the target definition file uses snapshot versions for LSP4E. The latest LSP4E snapshot version uses LSP4J version `[0.22.0,0.23.0)`, but the latest LSP4E release version 0.24.8 uses LSP4J version `[0.21.0,0.22.0)`. These LSP4J versions are incompatible (due to some classes that were moved from one package to another). Since CDT LSP needs LSP4E 0.24.8, I think, we have to stick with LSP4J version 0.21.0.
I am not sure about the Docker repository location …

Adapt target platform definition for using release versions

---

CHANGELOG.md

In light of conversation in https://github.com/eclipse-cdt/cdt-lsp/pull/265#issuecomment-1957738075 lets make it explicit that there is no API guarantee yet.

Add API guarantee note

---

.github/workflows/tycho-build.yaml
.gitignore
.mvn/extensions.xml
pom.xml
releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

With recent changes to Linuxtools we need to start building against 4.31 I-builds.
The alternative is to not use nightly for linuxtools.
Requires that
https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/pull/324 be merged and a new build completes.
Fixes #269

Update to latest dependencies

---

Jenkinsfile
jenkins/pod-templates/cdt-full-pod-plus-eclipse-install.yaml

The recent change in #271 started needing a newer version of Maven. CDT already had that change made in so I make the same change here.
With https://github.com/eclipse-cdt/.eclipsefdn/pull/7 we can push to origin directly, letting the branch be tested with Jenkins before being merged. So this change is running as https://ci.eclipse.org/cdt/job/cdt-lsp/job/jonah%252Ffix-jenkins-build2/ right now.

Bring cdt-lsp Jenkins configuration up to date with CDT's one

---

bundles/org.eclipse.cdt.lsp.clangd/plugin.xml

otherwise to 'Find Refernces' entries were made in the generic editor context menu.

fix: add visibleWhen to find references menu entry

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/messages/LspUiMessages.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/messages/LspUiMessages.properties
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/EditorConfigurationPage.java

to let the user change the content assist settings for the lsp based C/C++ editor.
fixes #300

[#300] Add link to Generic Text Editors preference page

---

bundles/org.eclipse.cdt.lsp/plugin.xml

I also adapted the icon shown for a file opened in the CDT LSP editor, depending on whether it is a header file or a source file.

Fix #301 Also adapt the editor's icon depending on open file type

---

jenkins/pod-templates/cdt-full-pod-plus-eclipse-install.yaml

This synchronizes cdt-lsp to https://github.com/eclipse-cdt/cdt/pull/767 and makes the JIPP behave the same as GitHub actions that was changed in https://github.com/eclipse-cdt/cdt-lsp/pull/304

Update docker image to Java 21 by default

---

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

Use orbit-aggregation/2024-06.
There is this new report:
https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/cdt-lsp/REPORT.md
This commit is effectively just a copy-and-paste (other than the aggregation update) of this:
https://raw.githubusercontent.com/eclipse-orbit/orbit-simrel/main/report/maven-osgi/cdt-lsp/updated.target

Update direct-from-maven dependencies to latest available minor versions

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/util/LspUtils.java

getEditor can return null.
may be a fix for #320

[#320] prevent possible NPE in isFileOpenedInLspEditor

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/ui/navigator/CSymbolsContentProvider.java

...to prevent a longer UI freeze. More children can be shown in navigator Treeview in Project Explorer via 'Show next x items from remaining y'. The limit will be taken from the 'Initial maximum number of elements shown in views' in the General preference page.
fixes #305

[#305] limit TU children/symbols to be added

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/ui/navigator/SymbolsManager.java

- ensures that refreshTreeContentFromLS can be performed again, when prior attempts failed due to languageServer.get timeout
- increase timeout for languageServer.get since 500ms can be too short when the LS is not running and has to be started.
fixes #329

[#329] reset CompileUnit dirty flag only when fetch was successful

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/ui/navigator/SymbolsManager.java

- because the same SymbolsManager instance can be called from several jobs (threads) started by the DeferredTreeContentManager.
fixes a technical depth from PR #328

[#328] make refreshTreeContentFromLS reentrant

---

Jenkinsfile

These can be reenabled if diagnosing a problem, but shouldn't be there all the time as they slow down
the build and make the build output huge

Remove debug log messages from maven

---

bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/editor/CEditorAssociationOverride.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/util/LspUtils.java

...when no other editor is opened to inherit editor type from
fixes #342

[#342] use default editor to open external file

---

bundles/org.eclipse.cdt.lsp/plugin.xml

- currently the page is also in other project types visible
- adds the 'format' as well as other c editor keywords to the save actions page to improve lookup of preference/properties settings.
fixes #355

[#355] Disable 'Save Actions' property page when no C/C++ project

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/utils/ClangFormatUtils.java

to prevent  conflicting scheduling rules while accessing a resource.
fixes #360

[#360] create .clang-format file in workspace job

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/editor/EditorPreferenceInitializer.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/editor/FormatOnSave.java

increase timeout from 5 to 30 seconds. Fetching formatting regions from the language server for large files (>20k lines of code) can take more than 5 sec.
fixes #362

[#362] increase timeout for fetching format regions from LS

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ClangdConfigurationPage.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/util/LspUtils.java

due to this [LSP4E change 1044 ](https://github.com/eclipse/lsp4e/pull/1044)in LSP4E the restart of a LS, after an exception occurred during the start of the LS, is not possible anymore. This will be fixed.

fix LS restart after exception

---

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

Points to final CDT repo
I had done a cleanup on the CDT repos and removed all the pre-release artifacts from download.eclipse.org leading to a failure here that needed an update.

Update target platform

---

bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/server/AsyncStreamPipe.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/server/CLanguageServerStreamConnectionProvider.java

[401] stop piper thread via flag

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/format/ClangFormatFileMonitor.java

this improves the validation check of .clang-format files since only errors are printed to clangd stderr stream.

log errors only

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/console/ClangdConsole.java

to prevent OOM exception in Eclipse

limit text buffer in Clangd console

---

bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/l10n/bundle.properties
bundles/org.eclipse.cdt.lsp.clangd/plugin.xml

when no category is set, the key is not shown in the preference page. (filtered by default)
fixes #369

[#369] add missing command category

---

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/l10n/bundle.properties
bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/org.eclipse.cdt.lsp.clangd.internal.config.ClangdConfigurationAccess.xml
bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/org.eclipse.cdt.lsp.clangd.internal.config.ClangdContentAssistConfigurationAccess.xml
bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/org.eclipse.cdt.lsp.clangd.internal.config.ClangdContentAssistMetadataDefaults.xml
bundles/org.eclipse.cdt.lsp.clangd/plugin.xml
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdContentAssistConfiguration.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdContentAssistMetadata.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdContentAssistOptions.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdContentAssistQualifier.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdConfigurationAccess.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdContentAssistConfigurationAccess.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdContentAssistMetadataDefaults.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdContentAssistPreferenceInitializer.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdContentAssistPreferredOptions.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ClangdConfigurationPage.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ContentAssistConfigurationArea.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ContentAssistConfigurationPage.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/LspEditorUiMessages.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/LspEditorUiMessages.properties
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/messages/LspUiMessages.properties
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/util/LspUtils.java

with `Fill function arguments and show guessed arguments` option to comply with old C/C++ editor Content Assist preference page. The option is only available on workspace level (preference page only) since we currently support only a single LS per workspace.
fixes #418

[#418] add Content Assist preference page to editor

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdMetadata.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdMetadataDefaults.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdPreferredOptions.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ClangdConfigurationArea.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ClangdConfigurationPage.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ContentAssistConfigurationArea.java
bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/TestUtils.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/editor/EditorMetadata.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/editor/EditorMetadataDefaults.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/editor/EditorPreferredOptions.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/ui/EditorConfigurationArea.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/ui/SaveActionsConfigurationArea.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/ui/SaveActionsConfigurationPage.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/ui/EditorConfigurationPage.java
examples/org.eclipse.cdt.lsp.examples.preferences/src/org/eclipse/cdt/lsp/examples/preferences/MyClangdOptionsDefaults.java
tests/org.eclipse.cdt.lsp.clangd.tests/src/org/eclipse/cdt/lsp/clangd/tests/TestUtils.java

* extract predefined preference metadata to another "noimplement" interface

[#410] Evolve options API without bumping major version every time

---

bundles/org.eclipse.cdt.lsp.clangd/OSGI-INF/org.eclipse.cdt.lsp.clangd.internal.config.DefaultClangdCompilationDatabaseSettings.xml
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdMetadata.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdOptions.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdPreferredOptions.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/DefaultClangdCompilationDatabaseSettings.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/ClangdConfigurationArea.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/LspEditorUiMessages.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/ui/LspEditorUiMessages.properties

..depending on active build configuration or cmake build type.
fixes #357

[#357] add option to enable the database update in .clangd file

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdConfigurationAccess.java

...as argument. Because some clangd versions cannot handle true/false strings as argument.
fixes #438

[#438] use 0/1 instead of false/true for --function-arg-placeholders

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangdMetadata.java

Check for clangd in MinGW installation

---

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/ClangFormatFile.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/format/ClangFormatFileMonitor.java
bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangFormatFileHandler.java

Instead of creating a .clang-format file for each project, CDT LSP now would check if there is a .clang-format file in some of the project's parent folders and use that. This way, multi-project directory structures (multi-project git repos) can offer common settings in their root folder that apply to all contained projects.

Fix #436 Search .clang-format file in parent folders, before creating it

---

CHANGELOG.md

I am not sure the ongoing value of this changelog, for now at least I have made it point back at the milestone's issues.

Add 2.0.0 and 3.0.0 to changelog

---

bundles/org.eclipse.cdt.lsp.clangd/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp.doc/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
examples/org.eclipse.cdt.lsp.examples.preferences/META-INF/MANIFEST.MF
features/org.eclipse.cdt.lsp.feature/feature.xml
pom.xml
releng/org.eclipse.cdt.lsp.repository/pom.xml

~Note that the MANIFEST.MF versions are not bumped - they should only be changed along with API changes following semantic version conventions.~
Scratch that - because we don't have jgit timestamps enabled the qualifier is just the build timestamp. Which means all bundles need to be bumped. For the branch that means +0.0.1, for the main that means +0.0.100.

Prepare repo for CDT LSP 3.1.0

---

bundles/org.eclipse.cdt.lsp.test/src/org/eclipse/cdt/lsp/test/internal/server/HasLanguageServerPropertyTesterTest.java
bundles/org.eclipse.cdt.lsp/META-INF/MANIFEST.MF
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/ui/navigator/SymbolsManager.java
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/util/LspUtils.java

[#446] Show symbols of external C/C++ files

---

bundles/org.eclipse.cdt.lsp.clangd/src/org/eclipse/cdt/lsp/clangd/internal/config/ClangdConfigFileChecker.java

Do not throw an exception when starting a new document in .clangd file via ---.
fixes #469

[#469] parse all yaml documents in .clangd file

---

bundles/org.eclipse.cdt.lsp/OSGI-INF/l10n/bundle.properties
bundles/org.eclipse.cdt.lsp/plugin.xml
bundles/org.eclipse.cdt.lsp/src/org/eclipse/cdt/lsp/internal/editor/CLspEditor.java

- introduce and use own context for C/C++ Editor (LSP)
fixes #497

[#497] bind F12 to Open Hyperlink in MS Visual Studio scheme

---

releng/org.eclipse.cdt.lsp.target/org.eclipse.cdt.lsp.target.target

Note that we aren't using latest versions of dependencies because we want CDT LSP to work against slightly older Eclipse installs.

Make sure we build release against released versions of dependencies
